pipeline {
    agent any

    tools {
        maven "maven3"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/DeepanshuNegi123/jenkins.git'
            }
        }

        stage('Build + Test + Package') {
            steps {
                dir('project2') {
                    bat 'mvn clean compile'
                    bat 'mvn test'
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo "✅ Build Successful"
        }

        failure {
            echo "❌ Build Failed"
        }
    }
}